public class Mensagens {
    public static void main(String[] args) {

        System.out.println("Meu nome é Luca Salvadego");
        System.out.println();
        System.out.println("A soma de 2 + 2 = 4");
        System.out.println();
        System.out.println("**********");
        System.out.println();
        System.out.println("*****");
        System.out.println("*   *");
        System.out.println("*   *");
        System.out.println("*   *");
        System.out.println("*****");
        System.out.println();
        System.out.println("     #");
        System.out.println("    # #");
        System.out.println("   #   #");
        System.out.println("  #     #");
        System.out.println(" #       #");
        System.out.println("###########");
        System.out.println();
        System.out.println("   .   ");
        System.out.println("  . .  ");
        System.out.println(" .   . ");
        System.out.println(".     .");
        System.out.println(" .   . ");
        System.out.println("  . .  ");
        System.out.println("   .   ");
        System.out.println();
        System.out.println("    $");
        System.out.println("   $ $");
        System.out.println("  $   $");
        System.out.println(" $     $");
        System.out.println("$$$$$$$$$");
        System.out.println();
        System.out.println("   *   ");
        System.out.println("  ***  ");
        System.out.println("*******");
        System.out.println(" ***** ");
        System.out.println("*******");
        System.out.println(" ***** ");
        System.out.println("*******");
        System.out.println("   *   ");
        System.out.println();
        System.out.println("  ***   *** ");
        System.out.println(" *   ***   *");
        System.out.println("  *       * ");
        System.out.println("   *     *  ");
        System.out.println("    *   *   ");
        System.out.println("     * *    ");
        System.out.println("      *     ");
        System.out.println();
        System.out.println("   .... ");
        System.out.println(" .      .");
        System.out.println(" .      .");
        System.out.println(" .      .");
        System.out.println("   .... ");
        System.out.println();
        System.out.println("    >");
        System.out.println("    >>>");
        System.out.println(">>>>>>>>");
        System.out.println("    >>>");
        System.out.println("    >");
        System.out.println();
        System.out.println("   <");
        System.out.println(" <<<");
        System.out.println("<<<<<<<<");
        System.out.println(" <<<");
        System.out.println("   <");
        System.out.println();
        System.out.println("   *   ");
        System.out.println("*******");
        System.out.println(" ***** ");
        System.out.println(" *   * ");
        System.out.println();
        System.out.println("# # # # ");
        System.out.println(" # # # #");
        System.out.println("# # # # ");
        System.out.println(" # # # #");
        System.out.println("# # # # ");
        System.out.println(" # # # #");
        System.out.println("# # # # ");
        System.out.println(" # # # #");
        System.out.println();
        System.out.println("*************");
        System.out.println(" *         *");
        System.out.println("  *       *");
        System.out.println("   *     *");
        System.out.println("    *   *");
        System.out.println("     * *");
        System.out.println("      *");

    }
}
